-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reduce32 is
port (
    ap_ready : OUT STD_LOGIC;
    a : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (24 downto 0) );
end;


architecture behav of reduce32 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal t_fu_20_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_fu_28_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_s_fu_42_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal t_cast_fu_24_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal a_assign_cast_fu_38_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_26_fu_54_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_cast_fu_50_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_35_cast_fu_60_p1 : STD_LOGIC_VECTOR (24 downto 0);


begin



    a_assign_cast_fu_38_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_28_p4),24));
    ap_ready <= ap_const_logic_1;
    ap_return <= std_logic_vector(unsigned(tmp_cast_fu_50_p1) + unsigned(tmp_35_cast_fu_60_p1));
    t_cast_fu_24_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_fu_20_p1),24));
    t_fu_20_p1 <= a(23 - 1 downto 0);
    tmp_26_fu_54_p2 <= std_logic_vector(unsigned(t_cast_fu_24_p1) - unsigned(a_assign_cast_fu_38_p1));
        tmp_35_cast_fu_60_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_26_fu_54_p2),25));

    tmp_cast_fu_50_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_42_p3),25));
    tmp_fu_28_p4 <= a(31 downto 23);
    tmp_s_fu_42_p3 <= (tmp_fu_28_p4 & ap_const_lv13_0);
end behav;
