// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module keccak_squeezeblocks_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        h_address0,
        h_ce0,
        h_we0,
        h_d0,
        nblocks,
        s_address0,
        s_ce0,
        s_we0,
        s_d0,
        s_q0,
        s_address1,
        s_ce1,
        s_we1,
        s_d1,
        s_q1
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] h_address0;
output   h_ce0;
output   h_we0;
output  [7:0] h_d0;
input  [3:0] nblocks;
output  [4:0] s_address0;
output   s_ce0;
output   s_we0;
output  [63:0] s_d0;
input  [63:0] s_q0;
output  [4:0] s_address1;
output   s_ce1;
output   s_we1;
output  [63:0] s_d1;
input  [63:0] s_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg h_ce0;
reg h_we0;
reg[4:0] s_address0;
reg s_ce0;
reg s_we0;
reg s_ce1;
reg s_we1;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] i_38_fu_145_p2;
reg   [4:0] i_38_reg_249;
wire    ap_CS_fsm_state4;
wire   [0:0] exitcond_fu_139_p2;
wire   [9:0] p_rec_fu_156_p2;
wire   [3:0] nblocks_assign_fu_162_p2;
wire   [7:0] tmp_98_fu_168_p3;
reg   [7:0] tmp_98_reg_269;
wire    ap_CS_fsm_state5;
reg   [63:0] s_load_reg_274;
wire   [3:0] i_39_fu_182_p2;
wire    ap_CS_fsm_state6;
wire    grp_KeccakF1600_StatePer_fu_125_ap_start;
wire    grp_KeccakF1600_StatePer_fu_125_ap_done;
wire    grp_KeccakF1600_StatePer_fu_125_ap_idle;
wire    grp_KeccakF1600_StatePer_fu_125_ap_ready;
wire   [4:0] grp_KeccakF1600_StatePer_fu_125_state_address0;
wire    grp_KeccakF1600_StatePer_fu_125_state_ce0;
wire    grp_KeccakF1600_StatePer_fu_125_state_we0;
wire   [63:0] grp_KeccakF1600_StatePer_fu_125_state_d0;
wire   [4:0] grp_KeccakF1600_StatePer_fu_125_state_address1;
wire    grp_KeccakF1600_StatePer_fu_125_state_ce1;
wire    grp_KeccakF1600_StatePer_fu_125_state_we1;
wire   [63:0] grp_KeccakF1600_StatePer_fu_125_state_d1;
reg   [3:0] nblocks_assign_1_reg_80;
reg   [9:0] p_0_rec_reg_90;
reg   [4:0] i_reg_102;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_i_fu_176_p2;
reg   [3:0] i_i_reg_114;
reg    grp_KeccakF1600_StatePer_fu_125_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_97_fu_133_p2;
wire   [63:0] tmp_s_fu_151_p1;
wire   [63:0] sum_i_cast_fu_233_p1;
wire   [2:0] tmp_638_fu_188_p1;
wire   [5:0] tmp_i_60_fu_192_p3;
wire   [63:0] tmp_17_i_fu_200_p1;
wire   [63:0] tmp_18_i_fu_204_p2;
wire   [7:0] tmp_20_i_cast_fu_214_p1;
wire   [7:0] tmp_fu_218_p2;
wire   [9:0] tmp_cast_fu_223_p1;
wire   [9:0] sum_i_fu_227_p2;
reg   [5:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_KeccakF1600_StatePer_fu_125_ap_start_reg = 1'b0;
end

KeccakF1600_StatePer grp_KeccakF1600_StatePer_fu_125(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_KeccakF1600_StatePer_fu_125_ap_start),
    .ap_done(grp_KeccakF1600_StatePer_fu_125_ap_done),
    .ap_idle(grp_KeccakF1600_StatePer_fu_125_ap_idle),
    .ap_ready(grp_KeccakF1600_StatePer_fu_125_ap_ready),
    .state_address0(grp_KeccakF1600_StatePer_fu_125_state_address0),
    .state_ce0(grp_KeccakF1600_StatePer_fu_125_state_ce0),
    .state_we0(grp_KeccakF1600_StatePer_fu_125_state_we0),
    .state_d0(grp_KeccakF1600_StatePer_fu_125_state_d0),
    .state_q0(s_q0),
    .state_address1(grp_KeccakF1600_StatePer_fu_125_state_address1),
    .state_ce1(grp_KeccakF1600_StatePer_fu_125_state_ce1),
    .state_we1(grp_KeccakF1600_StatePer_fu_125_state_we1),
    .state_d1(grp_KeccakF1600_StatePer_fu_125_state_d1),
    .state_q1(s_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_KeccakF1600_StatePer_fu_125_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_97_fu_133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_KeccakF1600_StatePer_fu_125_ap_start_reg <= 1'b1;
        end else if ((grp_KeccakF1600_StatePer_fu_125_ap_ready == 1'b1)) begin
            grp_KeccakF1600_StatePer_fu_125_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        i_i_reg_114 <= i_39_fu_182_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        i_i_reg_114 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_fu_176_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        i_reg_102 <= i_38_reg_249;
    end else if (((grp_KeccakF1600_StatePer_fu_125_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_102 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_139_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        nblocks_assign_1_reg_80 <= nblocks_assign_fu_162_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        nblocks_assign_1_reg_80 <= nblocks;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_139_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_rec_reg_90 <= p_rec_fu_156_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_0_rec_reg_90 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_38_reg_249 <= i_38_fu_145_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_load_reg_274 <= s_q0;
        tmp_98_reg_269[7 : 3] <= tmp_98_fu_168_p3[7 : 3];
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_97_fu_133_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_97_fu_133_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        h_ce0 = 1'b1;
    end else begin
        h_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        h_we0 = 1'b1;
    end else begin
        h_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        s_address0 = tmp_s_fu_151_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        s_address0 = grp_KeccakF1600_StatePer_fu_125_state_address0;
    end else begin
        s_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        s_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        s_ce0 = grp_KeccakF1600_StatePer_fu_125_state_ce0;
    end else begin
        s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        s_ce1 = grp_KeccakF1600_StatePer_fu_125_state_ce1;
    end else begin
        s_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        s_we0 = grp_KeccakF1600_StatePer_fu_125_state_we0;
    end else begin
        s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        s_we1 = grp_KeccakF1600_StatePer_fu_125_state_we1;
    end else begin
        s_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_97_fu_133_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_KeccakF1600_StatePer_fu_125_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond_fu_139_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((tmp_i_fu_176_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign exitcond_fu_139_p2 = ((i_reg_102 == 5'd17) ? 1'b1 : 1'b0);

assign grp_KeccakF1600_StatePer_fu_125_ap_start = grp_KeccakF1600_StatePer_fu_125_ap_start_reg;

assign h_address0 = sum_i_cast_fu_233_p1;

assign h_d0 = tmp_18_i_fu_204_p2[7:0];

assign i_38_fu_145_p2 = (i_reg_102 + 5'd1);

assign i_39_fu_182_p2 = (i_i_reg_114 + 4'd1);

assign nblocks_assign_fu_162_p2 = ($signed(nblocks_assign_1_reg_80) + $signed(4'd15));

assign p_rec_fu_156_p2 = (p_0_rec_reg_90 + 10'd136);

assign s_address1 = grp_KeccakF1600_StatePer_fu_125_state_address1;

assign s_d0 = grp_KeccakF1600_StatePer_fu_125_state_d0;

assign s_d1 = grp_KeccakF1600_StatePer_fu_125_state_d1;

assign sum_i_cast_fu_233_p1 = sum_i_fu_227_p2;

assign sum_i_fu_227_p2 = (p_0_rec_reg_90 + tmp_cast_fu_223_p1);

assign tmp_17_i_fu_200_p1 = tmp_i_60_fu_192_p3;

assign tmp_18_i_fu_204_p2 = s_load_reg_274 >> tmp_17_i_fu_200_p1;

assign tmp_20_i_cast_fu_214_p1 = i_i_reg_114;

assign tmp_638_fu_188_p1 = i_i_reg_114[2:0];

assign tmp_97_fu_133_p2 = ((nblocks_assign_1_reg_80 == 4'd0) ? 1'b1 : 1'b0);

assign tmp_98_fu_168_p3 = {{i_reg_102}, {3'd0}};

assign tmp_cast_fu_223_p1 = tmp_fu_218_p2;

assign tmp_fu_218_p2 = (tmp_20_i_cast_fu_214_p1 + tmp_98_reg_269);

assign tmp_i_60_fu_192_p3 = {{tmp_638_fu_188_p1}, {3'd0}};

assign tmp_i_fu_176_p2 = ((i_i_reg_114 == 4'd8) ? 1'b1 : 1'b0);

assign tmp_s_fu_151_p1 = i_reg_102;

always @ (posedge ap_clk) begin
    tmp_98_reg_269[2:0] <= 3'b000;
end

endmodule //keccak_squeezeblocks_1
