// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _reduce32_HH_
#define _reduce32_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct reduce32 : public sc_module {
    // Port declarations 3
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > a;
    sc_out< sc_lv<25> > ap_return;


    // Module declarations
    reduce32(sc_module_name name);
    SC_HAS_PROCESS(reduce32);

    ~reduce32();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<23> > t_fu_20_p1;
    sc_signal< sc_lv<9> > tmp_fu_28_p4;
    sc_signal< sc_lv<22> > tmp_s_fu_42_p3;
    sc_signal< sc_lv<24> > t_cast_fu_24_p1;
    sc_signal< sc_lv<24> > a_assign_cast_fu_38_p1;
    sc_signal< sc_lv<24> > tmp_26_fu_54_p2;
    sc_signal< sc_lv<25> > tmp_cast_fu_50_p1;
    sc_signal< sc_lv<25> > tmp_35_cast_fu_60_p1;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<13> ap_const_lv13_0;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_a_assign_cast_fu_38_p1();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_t_cast_fu_24_p1();
    void thread_t_fu_20_p1();
    void thread_tmp_26_fu_54_p2();
    void thread_tmp_35_cast_fu_60_p1();
    void thread_tmp_cast_fu_50_p1();
    void thread_tmp_fu_28_p4();
    void thread_tmp_s_fu_42_p3();
};

}

using namespace ap_rtl;

#endif
