// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "invntt_frominvmont.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic invntt_frominvmont::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic invntt_frominvmont::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state1 = "1";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state2 = "10";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state3 = "100";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state4 = "1000";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state5 = "10000";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state6 = "100000";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state7 = "1000000";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state8 = "10000000";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state9 = "100000000";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state10 = "1000000000";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state11 = "10000000000";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state12 = "100000000000";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<17> invntt_frominvmont::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_5 = "101";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_D = "1101";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_1 = "1";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_2 = "10";
const sc_lv<1> invntt_frominvmont::ap_const_lv1_1 = "1";
const sc_lv<1> invntt_frominvmont::ap_const_lv1_0 = "0";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_3 = "11";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_4 = "100";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_7 = "111";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_8 = "1000";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_9 = "1001";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_A = "1010";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_C = "1100";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_E = "1110";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_F = "1111";
const sc_lv<9> invntt_frominvmont::ap_const_lv9_1 = "1";
const sc_lv<10> invntt_frominvmont::ap_const_lv10_0 = "0000000000";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_B = "1011";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_10 = "10000";
const sc_lv<9> invntt_frominvmont::ap_const_lv9_0 = "000000000";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_6 = "110";
const sc_lv<8> invntt_frominvmont::ap_const_lv8_0 = "00000000";
const sc_lv<2> invntt_frominvmont::ap_const_lv2_0 = "00";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_7FE00100 = "1111111111000000000000100000000";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_FC7FDFFF = "11111100011111111101111111111111";
const sc_lv<55> invntt_frominvmont::ap_const_lv55_7FE001 = "11111111110000000000001";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_20 = "100000";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_37 = "110111";
const sc_lv<9> invntt_frominvmont::ap_const_lv9_100 = "100000000";
const sc_lv<32> invntt_frominvmont::ap_const_lv32_801C06 = "100000000001110000000110";
const sc_lv<49> invntt_frominvmont::ap_const_lv49_A3FA = "1010001111111010";
const bool invntt_frominvmont::ap_const_boolean_1 = true;

invntt_frominvmont::invntt_frominvmont(sc_module_name name) : sc_module(name), mVcdFile(0) {
    zetas_inv_U = new invntt_frominvmoneOg("zetas_inv_U");
    zetas_inv_U->clk(ap_clk);
    zetas_inv_U->reset(ap_rst);
    zetas_inv_U->address0(zetas_inv_address0);
    zetas_inv_U->ce0(zetas_inv_ce0);
    zetas_inv_U->q0(zetas_inv_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_assign_21_cast2_fu_374_p1);
    sensitive << ( a_assign_s_reg_574 );

    SC_METHOD(thread_a_assign_cast1_fu_452_p1);
    sensitive << ( a_assign_reg_613 );

    SC_METHOD(thread_a_assign_fu_437_p0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( a_assign_fu_437_p00 );

    SC_METHOD(thread_a_assign_fu_437_p00);
    sensitive << ( tmp_243_cast_fu_433_p0 );

    SC_METHOD(thread_a_assign_fu_437_p2);
    sensitive << ( a_assign_fu_437_p0 );

    SC_METHOD(thread_a_assign_s_fu_351_p0);
    sensitive << ( tmp_241_cast_reg_540 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_a_assign_s_fu_351_p1);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( a_assign_s_fu_351_p10 );

    SC_METHOD(thread_a_assign_s_fu_351_p10);
    sensitive << ( tmp_163_reg_569 );

    SC_METHOD(thread_a_assign_s_fu_351_p2);
    sensitive << ( a_assign_s_fu_351_p0 );
    sensitive << ( a_assign_s_fu_351_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_152_fu_401_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_152_fu_401_p2 );

    SC_METHOD(thread_icmp_fu_206_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_158_fu_196_p4 );

    SC_METHOD(thread_j_6_fu_407_p2);
    sensitive << ( j_1_reg_147 );

    SC_METHOD(thread_j_7_fu_315_p2);
    sensitive << ( j8_reg_138 );

    SC_METHOD(thread_j_cast4_fu_192_p1);
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_k_7_fu_226_p2);
    sensitive << ( k_fu_58 );

    SC_METHOD(thread_len_2_fu_220_p2);
    sensitive << ( len_reg_114 );

    SC_METHOD(thread_len_cast_fu_180_p1);
    sensitive << ( len_reg_114 );

    SC_METHOD(thread_p_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( p_addr_4_reg_548 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( p_addr_5_reg_553 );
    sensitive << ( p_addr_reg_602 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_170_cast_fu_286_p1 );

    SC_METHOD(thread_p_address1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( p_addr_5_reg_553 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_171_cast_fu_310_p1 );
    sensitive << ( tmp_168_cast_fu_422_p1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_p_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_p_ce1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_p_d0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_161_fu_329_p2 );
    sensitive << ( tmp_i_fu_396_p1 );
    sensitive << ( tmp_i4_fu_474_p1 );

    SC_METHOD(thread_p_we0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_start_cast_fu_264_p1);
    sensitive << ( start_fu_256_p3 );

    SC_METHOD(thread_start_fu_256_p3);
    sensitive << ( tmp_165_fu_246_p1 );
    sensitive << ( tmp_155_fu_240_p2 );
    sensitive << ( tmp_57_fu_250_p2 );

    SC_METHOD(thread_t_34_fu_427_p0);
    sensitive << ( reg_158 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_t_34_fu_427_p2);
    sensitive << ( t_34_fu_427_p0 );

    SC_METHOD(thread_t_35_fu_446_p0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( t_35_fu_446_p00 );

    SC_METHOD(thread_t_35_fu_446_p00);
    sensitive << ( t_34_reg_608 );

    SC_METHOD(thread_t_35_fu_446_p2);
    sensitive << ( t_35_fu_446_p0 );

    SC_METHOD(thread_t_36_fu_458_p2);
    sensitive << ( a_assign_cast1_fu_452_p1 );
    sensitive << ( t_48_cast_fu_455_p1 );

    SC_METHOD(thread_t_37_fu_360_p2);
    sensitive << ( tmp_173_reg_579 );

    SC_METHOD(thread_t_38_fu_368_p1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( t_38_fu_368_p10 );

    SC_METHOD(thread_t_38_fu_368_p10);
    sensitive << ( t_37_reg_584 );

    SC_METHOD(thread_t_38_fu_368_p2);
    sensitive << ( t_38_fu_368_p1 );

    SC_METHOD(thread_t_39_fu_380_p2);
    sensitive << ( a_assign_21_cast2_fu_374_p1 );
    sensitive << ( t_52_cast_fu_377_p1 );

    SC_METHOD(thread_t_48_cast_fu_455_p1);
    sensitive << ( t_35_reg_618 );

    SC_METHOD(thread_t_52_cast_fu_377_p1);
    sensitive << ( t_38_reg_589 );

    SC_METHOD(thread_tmp_152_fu_401_p2);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( j_1_reg_147 );

    SC_METHOD(thread_tmp_153_fu_215_p1);
    sensitive << ( k_fu_58 );

    SC_METHOD(thread_tmp_154_fu_231_p2);
    sensitive << ( len_cast_reg_493 );
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_tmp_155_fu_240_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( j_reg_126 );
    sensitive << ( tmp_154_fu_231_p2 );

    SC_METHOD(thread_tmp_156_cast_fu_413_p1);
    sensitive << ( j_1_reg_147 );

    SC_METHOD(thread_tmp_157_fu_272_p2);
    sensitive << ( tmp_239_cast3_reg_530 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( j8_reg_138 );

    SC_METHOD(thread_tmp_158_fu_196_p4);
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_tmp_159_fu_417_p2);
    sensitive << ( tmp_166_cast_reg_486 );
    sensitive << ( tmp_156_cast_fu_413_p1 );

    SC_METHOD(thread_tmp_160_fu_464_p4);
    sensitive << ( t_36_fu_458_p2 );

    SC_METHOD(thread_tmp_161_fu_329_p2);
    sensitive << ( p_q0 );
    sensitive << ( p_q1 );

    SC_METHOD(thread_tmp_162_fu_336_p2);
    sensitive << ( reg_158 );

    SC_METHOD(thread_tmp_163_fu_342_p2);
    sensitive << ( p_q1 );
    sensitive << ( tmp_162_fu_336_p2 );

    SC_METHOD(thread_tmp_164_fu_321_p2);
    sensitive << ( len_cast_reg_493 );
    sensitive << ( start_cast_reg_535 );

    SC_METHOD(thread_tmp_165_fu_246_p1);
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_tmp_166_cast_fu_171_p1);
    sensitive << ( tmp_s_fu_163_p3 );

    SC_METHOD(thread_tmp_166_fu_281_p2);
    sensitive << ( tmp_166_cast_reg_486 );
    sensitive << ( tmp_167_fu_277_p1 );

    SC_METHOD(thread_tmp_167_fu_277_p1);
    sensitive << ( j8_reg_138 );

    SC_METHOD(thread_tmp_168_cast_fu_422_p1);
    sensitive << ( tmp_159_fu_417_p2 );

    SC_METHOD(thread_tmp_168_fu_291_p1);
    sensitive << ( j8_reg_138 );

    SC_METHOD(thread_tmp_169_fu_295_p1);
    sensitive << ( len_reg_114 );

    SC_METHOD(thread_tmp_170_cast_fu_286_p1);
    sensitive << ( tmp_166_fu_281_p2 );

    SC_METHOD(thread_tmp_170_fu_299_p2);
    sensitive << ( tmp_169_fu_295_p1 );
    sensitive << ( tmp_168_fu_291_p1 );

    SC_METHOD(thread_tmp_171_cast_fu_310_p1);
    sensitive << ( tmp_171_fu_305_p2 );

    SC_METHOD(thread_tmp_171_fu_305_p2);
    sensitive << ( tmp_166_cast_reg_486 );
    sensitive << ( tmp_170_fu_299_p2 );

    SC_METHOD(thread_tmp_172_fu_386_p4);
    sensitive << ( t_39_fu_380_p2 );

    SC_METHOD(thread_tmp_173_fu_356_p1);
    sensitive << ( a_assign_s_fu_351_p2 );

    SC_METHOD(thread_tmp_239_cast3_fu_236_p1);
    sensitive << ( tmp_154_fu_231_p2 );

    SC_METHOD(thread_tmp_241_cast_fu_268_p1);
    sensitive << ( zetas_inv_q0 );

    SC_METHOD(thread_tmp_243_cast_fu_433_p0);
    sensitive << ( reg_158 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_tmp_57_fu_250_p2);
    sensitive << ( len_reg_114 );
    sensitive << ( tmp_165_fu_246_p1 );

    SC_METHOD(thread_tmp_fu_184_p3);
    sensitive << ( len_reg_114 );

    SC_METHOD(thread_tmp_i4_fu_474_p1);
    sensitive << ( tmp_160_fu_464_p4 );

    SC_METHOD(thread_tmp_i_fu_396_p1);
    sensitive << ( tmp_172_fu_386_p4 );

    SC_METHOD(thread_tmp_s_fu_163_p3);
    sensitive << ( p_offset );

    SC_METHOD(thread_zetas_inv_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_153_fu_215_p1 );

    SC_METHOD(thread_zetas_inv_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_fu_206_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_157_fu_272_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_152_fu_401_p2 );
    sensitive << ( tmp_fu_184_p3 );

    ap_CS_fsm = "00000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "invntt_frominvmont_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_address0, "(port)p_address0");
    sc_trace(mVcdFile, p_ce0, "(port)p_ce0");
    sc_trace(mVcdFile, p_we0, "(port)p_we0");
    sc_trace(mVcdFile, p_d0, "(port)p_d0");
    sc_trace(mVcdFile, p_q0, "(port)p_q0");
    sc_trace(mVcdFile, p_address1, "(port)p_address1");
    sc_trace(mVcdFile, p_ce1, "(port)p_ce1");
    sc_trace(mVcdFile, p_q1, "(port)p_q1");
    sc_trace(mVcdFile, p_offset, "(port)p_offset");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, zetas_inv_address0, "zetas_inv_address0");
    sc_trace(mVcdFile, zetas_inv_ce0, "zetas_inv_ce0");
    sc_trace(mVcdFile, zetas_inv_q0, "zetas_inv_q0");
    sc_trace(mVcdFile, reg_158, "reg_158");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, tmp_166_cast_fu_171_p1, "tmp_166_cast_fu_171_p1");
    sc_trace(mVcdFile, tmp_166_cast_reg_486, "tmp_166_cast_reg_486");
    sc_trace(mVcdFile, len_cast_fu_180_p1, "len_cast_fu_180_p1");
    sc_trace(mVcdFile, len_cast_reg_493, "len_cast_reg_493");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, j_cast4_fu_192_p1, "j_cast4_fu_192_p1");
    sc_trace(mVcdFile, j_cast4_reg_502, "j_cast4_reg_502");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_fu_206_p2, "icmp_fu_206_p2");
    sc_trace(mVcdFile, len_2_fu_220_p2, "len_2_fu_220_p2");
    sc_trace(mVcdFile, k_7_fu_226_p2, "k_7_fu_226_p2");
    sc_trace(mVcdFile, k_7_reg_525, "k_7_reg_525");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_239_cast3_fu_236_p1, "tmp_239_cast3_fu_236_p1");
    sc_trace(mVcdFile, tmp_239_cast3_reg_530, "tmp_239_cast3_reg_530");
    sc_trace(mVcdFile, start_cast_fu_264_p1, "start_cast_fu_264_p1");
    sc_trace(mVcdFile, start_cast_reg_535, "start_cast_reg_535");
    sc_trace(mVcdFile, tmp_241_cast_fu_268_p1, "tmp_241_cast_fu_268_p1");
    sc_trace(mVcdFile, tmp_241_cast_reg_540, "tmp_241_cast_reg_540");
    sc_trace(mVcdFile, p_addr_4_reg_548, "p_addr_4_reg_548");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_157_fu_272_p2, "tmp_157_fu_272_p2");
    sc_trace(mVcdFile, p_addr_5_reg_553, "p_addr_5_reg_553");
    sc_trace(mVcdFile, j_7_fu_315_p2, "j_7_fu_315_p2");
    sc_trace(mVcdFile, j_7_reg_559, "j_7_reg_559");
    sc_trace(mVcdFile, tmp_164_fu_321_p2, "tmp_164_fu_321_p2");
    sc_trace(mVcdFile, tmp_163_fu_342_p2, "tmp_163_fu_342_p2");
    sc_trace(mVcdFile, tmp_163_reg_569, "tmp_163_reg_569");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, a_assign_s_fu_351_p2, "a_assign_s_fu_351_p2");
    sc_trace(mVcdFile, a_assign_s_reg_574, "a_assign_s_reg_574");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_173_fu_356_p1, "tmp_173_fu_356_p1");
    sc_trace(mVcdFile, tmp_173_reg_579, "tmp_173_reg_579");
    sc_trace(mVcdFile, t_37_fu_360_p2, "t_37_fu_360_p2");
    sc_trace(mVcdFile, t_37_reg_584, "t_37_reg_584");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, t_38_fu_368_p2, "t_38_fu_368_p2");
    sc_trace(mVcdFile, t_38_reg_589, "t_38_reg_589");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, j_6_fu_407_p2, "j_6_fu_407_p2");
    sc_trace(mVcdFile, j_6_reg_597, "j_6_reg_597");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, p_addr_reg_602, "p_addr_reg_602");
    sc_trace(mVcdFile, tmp_152_fu_401_p2, "tmp_152_fu_401_p2");
    sc_trace(mVcdFile, t_34_fu_427_p2, "t_34_fu_427_p2");
    sc_trace(mVcdFile, t_34_reg_608, "t_34_reg_608");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, a_assign_fu_437_p2, "a_assign_fu_437_p2");
    sc_trace(mVcdFile, a_assign_reg_613, "a_assign_reg_613");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, t_35_fu_446_p2, "t_35_fu_446_p2");
    sc_trace(mVcdFile, t_35_reg_618, "t_35_reg_618");
    sc_trace(mVcdFile, len_reg_114, "len_reg_114");
    sc_trace(mVcdFile, j_reg_126, "j_reg_126");
    sc_trace(mVcdFile, tmp_fu_184_p3, "tmp_fu_184_p3");
    sc_trace(mVcdFile, j8_reg_138, "j8_reg_138");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, j_1_reg_147, "j_1_reg_147");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, tmp_153_fu_215_p1, "tmp_153_fu_215_p1");
    sc_trace(mVcdFile, tmp_170_cast_fu_286_p1, "tmp_170_cast_fu_286_p1");
    sc_trace(mVcdFile, tmp_171_cast_fu_310_p1, "tmp_171_cast_fu_310_p1");
    sc_trace(mVcdFile, tmp_168_cast_fu_422_p1, "tmp_168_cast_fu_422_p1");
    sc_trace(mVcdFile, k_fu_58, "k_fu_58");
    sc_trace(mVcdFile, tmp_161_fu_329_p2, "tmp_161_fu_329_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_i_fu_396_p1, "tmp_i_fu_396_p1");
    sc_trace(mVcdFile, tmp_i4_fu_474_p1, "tmp_i4_fu_474_p1");
    sc_trace(mVcdFile, tmp_s_fu_163_p3, "tmp_s_fu_163_p3");
    sc_trace(mVcdFile, tmp_158_fu_196_p4, "tmp_158_fu_196_p4");
    sc_trace(mVcdFile, tmp_154_fu_231_p2, "tmp_154_fu_231_p2");
    sc_trace(mVcdFile, tmp_165_fu_246_p1, "tmp_165_fu_246_p1");
    sc_trace(mVcdFile, tmp_155_fu_240_p2, "tmp_155_fu_240_p2");
    sc_trace(mVcdFile, tmp_57_fu_250_p2, "tmp_57_fu_250_p2");
    sc_trace(mVcdFile, start_fu_256_p3, "start_fu_256_p3");
    sc_trace(mVcdFile, tmp_167_fu_277_p1, "tmp_167_fu_277_p1");
    sc_trace(mVcdFile, tmp_166_fu_281_p2, "tmp_166_fu_281_p2");
    sc_trace(mVcdFile, tmp_169_fu_295_p1, "tmp_169_fu_295_p1");
    sc_trace(mVcdFile, tmp_168_fu_291_p1, "tmp_168_fu_291_p1");
    sc_trace(mVcdFile, tmp_170_fu_299_p2, "tmp_170_fu_299_p2");
    sc_trace(mVcdFile, tmp_171_fu_305_p2, "tmp_171_fu_305_p2");
    sc_trace(mVcdFile, tmp_162_fu_336_p2, "tmp_162_fu_336_p2");
    sc_trace(mVcdFile, a_assign_s_fu_351_p0, "a_assign_s_fu_351_p0");
    sc_trace(mVcdFile, a_assign_s_fu_351_p1, "a_assign_s_fu_351_p1");
    sc_trace(mVcdFile, t_38_fu_368_p1, "t_38_fu_368_p1");
    sc_trace(mVcdFile, a_assign_21_cast2_fu_374_p1, "a_assign_21_cast2_fu_374_p1");
    sc_trace(mVcdFile, t_52_cast_fu_377_p1, "t_52_cast_fu_377_p1");
    sc_trace(mVcdFile, t_39_fu_380_p2, "t_39_fu_380_p2");
    sc_trace(mVcdFile, tmp_172_fu_386_p4, "tmp_172_fu_386_p4");
    sc_trace(mVcdFile, tmp_156_cast_fu_413_p1, "tmp_156_cast_fu_413_p1");
    sc_trace(mVcdFile, tmp_159_fu_417_p2, "tmp_159_fu_417_p2");
    sc_trace(mVcdFile, t_34_fu_427_p0, "t_34_fu_427_p0");
    sc_trace(mVcdFile, tmp_243_cast_fu_433_p0, "tmp_243_cast_fu_433_p0");
    sc_trace(mVcdFile, a_assign_fu_437_p0, "a_assign_fu_437_p0");
    sc_trace(mVcdFile, t_35_fu_446_p0, "t_35_fu_446_p0");
    sc_trace(mVcdFile, a_assign_cast1_fu_452_p1, "a_assign_cast1_fu_452_p1");
    sc_trace(mVcdFile, t_48_cast_fu_455_p1, "t_48_cast_fu_455_p1");
    sc_trace(mVcdFile, t_36_fu_458_p2, "t_36_fu_458_p2");
    sc_trace(mVcdFile, tmp_160_fu_464_p4, "tmp_160_fu_464_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, a_assign_fu_437_p00, "a_assign_fu_437_p00");
    sc_trace(mVcdFile, a_assign_s_fu_351_p10, "a_assign_s_fu_351_p10");
    sc_trace(mVcdFile, t_35_fu_446_p00, "t_35_fu_446_p00");
    sc_trace(mVcdFile, t_38_fu_368_p10, "t_38_fu_368_p10");
#endif

    }
}

invntt_frominvmont::~invntt_frominvmont() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete zetas_inv_U;
}

void invntt_frominvmont::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        j8_reg_138 = j_7_reg_559.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        j8_reg_138 = j_cast4_reg_502.read();
    }
    if ((esl_seteq<1,1,1>(tmp_fu_184_p3.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        j_1_reg_147 = ap_const_lv9_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        j_1_reg_147 = j_6_reg_597.read();
    }
    if ((esl_seteq<1,1,1>(tmp_fu_184_p3.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        j_reg_126 = ap_const_lv10_0;
    } else if ((esl_seteq<1,1,1>(tmp_157_fu_272_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        j_reg_126 = tmp_164_fu_321_p2.read();
    }
    if ((esl_seteq<1,1,1>(tmp_157_fu_272_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        k_fu_58 = k_7_reg_525.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        k_fu_58 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(icmp_fu_206_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        len_reg_114 = len_2_fu_220_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        len_reg_114 = ap_const_lv9_1;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        reg_158 = p_q1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        reg_158 = p_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        a_assign_reg_613 = a_assign_fu_437_p2.read();
        t_35_reg_618 = t_35_fu_446_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        a_assign_s_reg_574 = a_assign_s_fu_351_p2.read();
        tmp_173_reg_579 = tmp_173_fu_356_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        j_6_reg_597 = j_6_fu_407_p2.read();
    }
    if ((esl_seteq<1,1,1>(tmp_157_fu_272_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        j_7_reg_559 = j_7_fu_315_p2.read();
        p_addr_4_reg_548 =  (sc_lv<10>) (tmp_170_cast_fu_286_p1.read());
        p_addr_5_reg_553 =  (sc_lv<10>) (tmp_171_cast_fu_310_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_cast4_reg_502 = j_cast4_fu_192_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        k_7_reg_525 = k_7_fu_226_p2.read();
        start_cast_reg_535 = start_cast_fu_264_p1.read();
        tmp_239_cast3_reg_530 = tmp_239_cast3_fu_236_p1.read();
        tmp_241_cast_reg_540 = tmp_241_cast_fu_268_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        len_cast_reg_493 = len_cast_fu_180_p1.read();
    }
    if ((esl_seteq<1,1,1>(tmp_152_fu_401_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        p_addr_reg_602 =  (sc_lv<10>) (tmp_168_cast_fu_422_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        t_34_reg_608 = t_34_fu_427_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        t_37_reg_584 = t_37_fu_360_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        t_38_reg_589 = t_38_fu_368_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        tmp_163_reg_569 = tmp_163_fu_342_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        tmp_166_cast_reg_486 = tmp_166_cast_fu_171_p1.read();
    }
}

void invntt_frominvmont::thread_a_assign_21_cast2_fu_374_p1() {
    a_assign_21_cast2_fu_374_p1 = esl_zext<56,55>(a_assign_s_reg_574.read());
}

void invntt_frominvmont::thread_a_assign_cast1_fu_452_p1() {
    a_assign_cast1_fu_452_p1 = esl_zext<56,49>(a_assign_reg_613.read());
}

void invntt_frominvmont::thread_a_assign_fu_437_p0() {
    a_assign_fu_437_p0 =  (sc_lv<32>) (a_assign_fu_437_p00.read());
}

void invntt_frominvmont::thread_a_assign_fu_437_p00() {
    a_assign_fu_437_p00 = esl_zext<49,32>(tmp_243_cast_fu_433_p0.read());
}

void invntt_frominvmont::thread_a_assign_fu_437_p2() {
    a_assign_fu_437_p2 = (!a_assign_fu_437_p0.read().is_01() || !ap_const_lv49_A3FA.is_01())? sc_lv<49>(): sc_biguint<32>(a_assign_fu_437_p0.read()) * sc_biguint<49>(ap_const_lv49_A3FA);
}

void invntt_frominvmont::thread_a_assign_s_fu_351_p0() {
    a_assign_s_fu_351_p0 =  (sc_lv<23>) (tmp_241_cast_reg_540.read());
}

void invntt_frominvmont::thread_a_assign_s_fu_351_p1() {
    a_assign_s_fu_351_p1 =  (sc_lv<32>) (a_assign_s_fu_351_p10.read());
}

void invntt_frominvmont::thread_a_assign_s_fu_351_p10() {
    a_assign_s_fu_351_p10 = esl_zext<55,32>(tmp_163_reg_569.read());
}

void invntt_frominvmont::thread_a_assign_s_fu_351_p2() {
    a_assign_s_fu_351_p2 = (!a_assign_s_fu_351_p0.read().is_01() || !a_assign_s_fu_351_p1.read().is_01())? sc_lv<55>(): sc_biguint<23>(a_assign_s_fu_351_p0.read()) * sc_biguint<32>(a_assign_s_fu_351_p1.read());
}

void invntt_frominvmont::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void invntt_frominvmont::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void invntt_frominvmont::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void invntt_frominvmont::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void invntt_frominvmont::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void invntt_frominvmont::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void invntt_frominvmont::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void invntt_frominvmont::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void invntt_frominvmont::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void invntt_frominvmont::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void invntt_frominvmont::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void invntt_frominvmont::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void invntt_frominvmont::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void invntt_frominvmont::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void invntt_frominvmont::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void invntt_frominvmont::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void invntt_frominvmont::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void invntt_frominvmont::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(tmp_152_fu_401_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void invntt_frominvmont::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void invntt_frominvmont::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(tmp_152_fu_401_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void invntt_frominvmont::thread_icmp_fu_206_p2() {
    icmp_fu_206_p2 = (!tmp_158_fu_196_p4.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_158_fu_196_p4.read() == ap_const_lv2_0);
}

void invntt_frominvmont::thread_j_6_fu_407_p2() {
    j_6_fu_407_p2 = (!j_1_reg_147.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(j_1_reg_147.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void invntt_frominvmont::thread_j_7_fu_315_p2() {
    j_7_fu_315_p2 = (!ap_const_lv32_1.is_01() || !j8_reg_138.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(j8_reg_138.read()));
}

void invntt_frominvmont::thread_j_cast4_fu_192_p1() {
    j_cast4_fu_192_p1 = esl_zext<32,10>(j_reg_126.read());
}

void invntt_frominvmont::thread_k_7_fu_226_p2() {
    k_7_fu_226_p2 = (!ap_const_lv32_1.is_01() || !k_fu_58.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(k_fu_58.read()));
}

void invntt_frominvmont::thread_len_2_fu_220_p2() {
    len_2_fu_220_p2 = (!ap_const_lv9_1.is_01())? sc_lv<9>(): len_reg_114.read() << (unsigned short)ap_const_lv9_1.to_uint();
}

void invntt_frominvmont::thread_len_cast_fu_180_p1() {
    len_cast_fu_180_p1 = esl_zext<10,9>(len_reg_114.read());
}

void invntt_frominvmont::thread_p_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        p_address0 = p_addr_reg_602.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        p_address0 = p_addr_5_reg_553.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_address0 = p_addr_4_reg_548.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        p_address0 =  (sc_lv<10>) (tmp_170_cast_fu_286_p1.read());
    } else {
        p_address0 = "XXXXXXXXXX";
    }
}

void invntt_frominvmont::thread_p_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        p_address1 =  (sc_lv<10>) (tmp_168_cast_fu_422_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        p_address1 = p_addr_5_reg_553.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        p_address1 =  (sc_lv<10>) (tmp_171_cast_fu_310_p1.read());
    } else {
        p_address1 = "XXXXXXXXXX";
    }
}

void invntt_frominvmont::thread_p_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        p_ce0 = ap_const_logic_1;
    } else {
        p_ce0 = ap_const_logic_0;
    }
}

void invntt_frominvmont::thread_p_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        p_ce1 = ap_const_logic_1;
    } else {
        p_ce1 = ap_const_logic_0;
    }
}

void invntt_frominvmont::thread_p_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        p_d0 = tmp_i4_fu_474_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        p_d0 = tmp_i_fu_396_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_d0 = tmp_161_fu_329_p2.read();
    } else {
        p_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void invntt_frominvmont::thread_p_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        p_we0 = ap_const_logic_1;
    } else {
        p_we0 = ap_const_logic_0;
    }
}

void invntt_frominvmont::thread_start_cast_fu_264_p1() {
    start_cast_fu_264_p1 = esl_zext<10,9>(start_fu_256_p3.read());
}

void invntt_frominvmont::thread_start_fu_256_p3() {
    start_fu_256_p3 = (!tmp_155_fu_240_p2.read()[0].is_01())? sc_lv<9>(): ((tmp_155_fu_240_p2.read()[0].to_bool())? tmp_165_fu_246_p1.read(): tmp_57_fu_250_p2.read());
}

void invntt_frominvmont::thread_t_34_fu_427_p0() {
    t_34_fu_427_p0 = reg_158.read();
}

void invntt_frominvmont::thread_t_34_fu_427_p2() {
    t_34_fu_427_p2 = (!t_34_fu_427_p0.read().is_01() || !ap_const_lv32_801C06.is_01())? sc_lv<32>(): sc_bigint<32>(t_34_fu_427_p0.read()) * sc_biguint<32>(ap_const_lv32_801C06);
}

void invntt_frominvmont::thread_t_35_fu_446_p0() {
    t_35_fu_446_p0 =  (sc_lv<32>) (t_35_fu_446_p00.read());
}

void invntt_frominvmont::thread_t_35_fu_446_p00() {
    t_35_fu_446_p00 = esl_zext<55,32>(t_34_reg_608.read());
}

void invntt_frominvmont::thread_t_35_fu_446_p2() {
    t_35_fu_446_p2 = (!t_35_fu_446_p0.read().is_01() || !ap_const_lv55_7FE001.is_01())? sc_lv<55>(): sc_biguint<32>(t_35_fu_446_p0.read()) * sc_biguint<55>(ap_const_lv55_7FE001);
}

void invntt_frominvmont::thread_t_36_fu_458_p2() {
    t_36_fu_458_p2 = (!a_assign_cast1_fu_452_p1.read().is_01() || !t_48_cast_fu_455_p1.read().is_01())? sc_lv<56>(): (sc_biguint<56>(a_assign_cast1_fu_452_p1.read()) + sc_biguint<56>(t_48_cast_fu_455_p1.read()));
}

void invntt_frominvmont::thread_t_37_fu_360_p2() {
    t_37_fu_360_p2 = (!ap_const_lv32_FC7FDFFF.is_01() || !tmp_173_reg_579.read().is_01())? sc_lv<32>(): sc_bigint<32>(ap_const_lv32_FC7FDFFF) * sc_bigint<32>(tmp_173_reg_579.read());
}

void invntt_frominvmont::thread_t_38_fu_368_p1() {
    t_38_fu_368_p1 =  (sc_lv<32>) (t_38_fu_368_p10.read());
}

void invntt_frominvmont::thread_t_38_fu_368_p10() {
    t_38_fu_368_p10 = esl_zext<55,32>(t_37_reg_584.read());
}

void invntt_frominvmont::thread_t_38_fu_368_p2() {
    t_38_fu_368_p2 = (!ap_const_lv55_7FE001.is_01() || !t_38_fu_368_p1.read().is_01())? sc_lv<55>(): sc_biguint<55>(ap_const_lv55_7FE001) * sc_biguint<32>(t_38_fu_368_p1.read());
}

void invntt_frominvmont::thread_t_39_fu_380_p2() {
    t_39_fu_380_p2 = (!a_assign_21_cast2_fu_374_p1.read().is_01() || !t_52_cast_fu_377_p1.read().is_01())? sc_lv<56>(): (sc_biguint<56>(a_assign_21_cast2_fu_374_p1.read()) + sc_biguint<56>(t_52_cast_fu_377_p1.read()));
}

void invntt_frominvmont::thread_t_48_cast_fu_455_p1() {
    t_48_cast_fu_455_p1 = esl_zext<56,55>(t_35_reg_618.read());
}

void invntt_frominvmont::thread_t_52_cast_fu_377_p1() {
    t_52_cast_fu_377_p1 = esl_zext<56,55>(t_38_reg_589.read());
}

void invntt_frominvmont::thread_tmp_152_fu_401_p2() {
    tmp_152_fu_401_p2 = (!j_1_reg_147.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(j_1_reg_147.read() == ap_const_lv9_100);
}

void invntt_frominvmont::thread_tmp_153_fu_215_p1() {
    tmp_153_fu_215_p1 = esl_zext<64,32>(k_fu_58.read());
}

void invntt_frominvmont::thread_tmp_154_fu_231_p2() {
    tmp_154_fu_231_p2 = (!len_cast_reg_493.read().is_01() || !j_reg_126.read().is_01())? sc_lv<10>(): (sc_biguint<10>(len_cast_reg_493.read()) + sc_biguint<10>(j_reg_126.read()));
}

void invntt_frominvmont::thread_tmp_155_fu_240_p2() {
    tmp_155_fu_240_p2 = (!j_reg_126.read().is_01() || !tmp_154_fu_231_p2.read().is_01())? sc_lv<1>(): (sc_biguint<10>(j_reg_126.read()) > sc_biguint<10>(tmp_154_fu_231_p2.read()));
}

void invntt_frominvmont::thread_tmp_156_cast_fu_413_p1() {
    tmp_156_cast_fu_413_p1 = esl_zext<12,9>(j_1_reg_147.read());
}

void invntt_frominvmont::thread_tmp_157_fu_272_p2() {
    tmp_157_fu_272_p2 = (!j8_reg_138.read().is_01() || !tmp_239_cast3_reg_530.read().is_01())? sc_lv<1>(): (sc_biguint<32>(j8_reg_138.read()) < sc_biguint<32>(tmp_239_cast3_reg_530.read()));
}

void invntt_frominvmont::thread_tmp_158_fu_196_p4() {
    tmp_158_fu_196_p4 = j_reg_126.read().range(9, 8);
}

void invntt_frominvmont::thread_tmp_159_fu_417_p2() {
    tmp_159_fu_417_p2 = (!tmp_166_cast_reg_486.read().is_01() || !tmp_156_cast_fu_413_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_166_cast_reg_486.read()) + sc_biguint<12>(tmp_156_cast_fu_413_p1.read()));
}

void invntt_frominvmont::thread_tmp_160_fu_464_p4() {
    tmp_160_fu_464_p4 = t_36_fu_458_p2.read().range(55, 32);
}

void invntt_frominvmont::thread_tmp_161_fu_329_p2() {
    tmp_161_fu_329_p2 = (!p_q0.read().is_01() || !p_q1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_q0.read()) + sc_biguint<32>(p_q1.read()));
}

void invntt_frominvmont::thread_tmp_162_fu_336_p2() {
    tmp_162_fu_336_p2 = (!ap_const_lv32_7FE00100.is_01() || !reg_158.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_7FE00100) + sc_biguint<32>(reg_158.read()));
}

void invntt_frominvmont::thread_tmp_163_fu_342_p2() {
    tmp_163_fu_342_p2 = (!tmp_162_fu_336_p2.read().is_01() || !p_q1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_162_fu_336_p2.read()) - sc_biguint<32>(p_q1.read()));
}

void invntt_frominvmont::thread_tmp_164_fu_321_p2() {
    tmp_164_fu_321_p2 = (!start_cast_reg_535.read().is_01() || !len_cast_reg_493.read().is_01())? sc_lv<10>(): (sc_biguint<10>(start_cast_reg_535.read()) + sc_biguint<10>(len_cast_reg_493.read()));
}

void invntt_frominvmont::thread_tmp_165_fu_246_p1() {
    tmp_165_fu_246_p1 = j_reg_126.read().range(9-1, 0);
}

void invntt_frominvmont::thread_tmp_166_cast_fu_171_p1() {
    tmp_166_cast_fu_171_p1 = esl_zext<12,11>(tmp_s_fu_163_p3.read());
}

void invntt_frominvmont::thread_tmp_166_fu_281_p2() {
    tmp_166_fu_281_p2 = (!tmp_166_cast_reg_486.read().is_01() || !tmp_167_fu_277_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_166_cast_reg_486.read()) + sc_biguint<12>(tmp_167_fu_277_p1.read()));
}

void invntt_frominvmont::thread_tmp_167_fu_277_p1() {
    tmp_167_fu_277_p1 = j8_reg_138.read().range(12-1, 0);
}

void invntt_frominvmont::thread_tmp_168_cast_fu_422_p1() {
    tmp_168_cast_fu_422_p1 = esl_zext<64,12>(tmp_159_fu_417_p2.read());
}

void invntt_frominvmont::thread_tmp_168_fu_291_p1() {
    tmp_168_fu_291_p1 = j8_reg_138.read().range(12-1, 0);
}

void invntt_frominvmont::thread_tmp_169_fu_295_p1() {
    tmp_169_fu_295_p1 = esl_zext<12,9>(len_reg_114.read());
}

void invntt_frominvmont::thread_tmp_170_cast_fu_286_p1() {
    tmp_170_cast_fu_286_p1 = esl_zext<64,12>(tmp_166_fu_281_p2.read());
}

void invntt_frominvmont::thread_tmp_170_fu_299_p2() {
    tmp_170_fu_299_p2 = (!tmp_169_fu_295_p1.read().is_01() || !tmp_168_fu_291_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_169_fu_295_p1.read()) + sc_biguint<12>(tmp_168_fu_291_p1.read()));
}

void invntt_frominvmont::thread_tmp_171_cast_fu_310_p1() {
    tmp_171_cast_fu_310_p1 = esl_zext<64,12>(tmp_171_fu_305_p2.read());
}

void invntt_frominvmont::thread_tmp_171_fu_305_p2() {
    tmp_171_fu_305_p2 = (!tmp_166_cast_reg_486.read().is_01() || !tmp_170_fu_299_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_166_cast_reg_486.read()) + sc_biguint<12>(tmp_170_fu_299_p2.read()));
}

void invntt_frominvmont::thread_tmp_172_fu_386_p4() {
    tmp_172_fu_386_p4 = t_39_fu_380_p2.read().range(55, 32);
}

void invntt_frominvmont::thread_tmp_173_fu_356_p1() {
    tmp_173_fu_356_p1 = a_assign_s_fu_351_p2.read().range(32-1, 0);
}

void invntt_frominvmont::thread_tmp_239_cast3_fu_236_p1() {
    tmp_239_cast3_fu_236_p1 = esl_zext<32,10>(tmp_154_fu_231_p2.read());
}

void invntt_frominvmont::thread_tmp_241_cast_fu_268_p1() {
    tmp_241_cast_fu_268_p1 = esl_zext<55,23>(zetas_inv_q0.read());
}

void invntt_frominvmont::thread_tmp_243_cast_fu_433_p0() {
    tmp_243_cast_fu_433_p0 = reg_158.read();
}

void invntt_frominvmont::thread_tmp_57_fu_250_p2() {
    tmp_57_fu_250_p2 = (!tmp_165_fu_246_p1.read().is_01() || !len_reg_114.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_165_fu_246_p1.read()) + sc_biguint<9>(len_reg_114.read()));
}

void invntt_frominvmont::thread_tmp_fu_184_p3() {
    tmp_fu_184_p3 = len_reg_114.read().range(8, 8);
}

void invntt_frominvmont::thread_tmp_i4_fu_474_p1() {
    tmp_i4_fu_474_p1 = esl_zext<32,24>(tmp_160_fu_464_p4.read());
}

void invntt_frominvmont::thread_tmp_i_fu_396_p1() {
    tmp_i_fu_396_p1 = esl_zext<32,24>(tmp_172_fu_386_p4.read());
}

void invntt_frominvmont::thread_tmp_s_fu_163_p3() {
    tmp_s_fu_163_p3 = esl_concat<3,8>(p_offset.read(), ap_const_lv8_0);
}

void invntt_frominvmont::thread_zetas_inv_address0() {
    zetas_inv_address0 =  (sc_lv<8>) (tmp_153_fu_215_p1.read());
}

void invntt_frominvmont::thread_zetas_inv_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        zetas_inv_ce0 = ap_const_logic_1;
    } else {
        zetas_inv_ce0 = ap_const_logic_0;
    }
}

void invntt_frominvmont::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(tmp_fu_184_p3.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(icmp_fu_206_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(tmp_157_fu_272_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(tmp_152_fu_401_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<17>) ("XXXXXXXXXXXXXXXXX");
            break;
    }
}

}

